variables:
  DOCKER_DRIVER: overlay
  PKG_PATH: github.com/jetstack-experimental/navigator

stages:
- build
- docker
- deploy

# configure $GOPATH correctly on all build stages
before_script:
  - mkdir -p "$GOPATH/src/$PKG_PATH" && rmdir "$GOPATH/src/$PKG_PATH"
  - ln -s "$(pwd)" "$GOPATH/src/$PKG_PATH"
  - cd "$GOPATH/src/$PKG_PATH"

test:golang:
  image: golang:1.8
  stage: build
  tags:
  - docker
  script:
  - make test

verify:golang:
  image: golang:1.8
  stage: build
  tags:
  - docker
  script:
  - make verify

build:golang:
  image: golang:1.8
  stage: build
  tags:
  - docker
  script:
  - make build
  artifacts:
    paths:
    - navigator_linux_amd64
