apiVersion: navigator.jetstack.io/v1alpha1
kind: CassandraCluster
metadata:
  name: demo
spec:
  sysctl:
  - vm.max_map_count=0
  nodePools:
  - name: RingNodes
    replicas: 3
  image:
    repository: gcr.io/google-samples/cassandra
    tag: v12
    pullPolicy: IfNotPresent
