apiVersion: v1
kind: Namespace
metadata:
  name: marshal
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: colonel
  namespace: marshal
  labels:
    app: colonel
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: colonel
    spec:
      containers:
      - name: colonel
        image: jetstackexperimental/colonel:latest
        imagePullPolicy: Always
