apiVersion: marshal.io/v1alpha1
kind: ElasticsearchCluster
metadata:
  name: demo
spec:
  version: '5.2.2'
  plugins:
  - name: "io.fabric8:elasticsearch-cloud-kubernetes:5.2.2"

  # NOTE: DO NOT SPECIFY MORE THAN ONE SYSCTL FOR NOW
  sysctl:
  - vm.max_map_count=262144

  image:
    repository: jetstackexperimental/pilot-elasticsearch
    tag: latest
    pullPolicy: Always
    ## This sets the group of the persistent volume created for
    ## the data nodes. This must be the same as the user that elasticsearch
    ## runs as within the container.
    fsGroup: 1000

  nodePools:
  - name: data
    replicas: 3

    roles:
    - data
    
    resources:
      requests:
        cpu: '500m'
        memory: 2Gi
      limits:
        cpu: '1'
        memory: 3Gi
    
    state:
      # stateful defines whether to create a StatefulSet or a Deployment
      stateful: true

      # persistent sets persistent storage config
      persistence:
        # enabled will only have an effect if stateful is also true. If true,
        # the persistentVolumeClaims block of the StatefulSet will be set
        enabled: true
        # size of the volume
        size: 10Gi
        # storageClass of the volume
        storageClass: "fast"

  - name: client
    replicas: 2

    roles:
    - client
    
    resources:
      requests:
        cpu: '1'
        memory: 2Gi
      limits:
        cpu: '2'
        memory: 4Gi

  - name: master
    replicas: 3

    roles:
    - master
    
    resources:
      requests:
        cpu: '1'
        memory: 2Gi
      limits:
        cpu: '2'
        memory: 4Gi
